name: "Building and testing"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone JMantic"
        uses: actions/checkout@v2

      - name: "Install Java"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: "Build JMantic"
        run: ./gradlew assemble

      - name: "Install Docker"
        uses: docker-practice/actions-setup-docker@master

      - name: "Pull Ostis docker-image"
        run: sudo docker pull ostis/ostis:0.6.0

      - name: "Run Tests"
        run: |
          sudo docker run -p 8000:8000 -p 8090:8090 ostis/ostis:0.6.0 sh ostis --all &
          sleep 60
          ./gradlew jacocoTestReport
